DROP TABLE IF EXISTS official_shifts;
DROP TABLE IF EXISTS last_minute_signups;

CREATE TABLE official_shifts (
    id INT PRIMARY KEY,
    volunteer_name TEXT,
    role TEXT,
    shift_time TEXT,
    age_group TEXT,
    code TEXT
);

CREATE TABLE last_minute_signups (
    id INT PRIMARY KEY,
    volunteer_name TEXT,
    assigned_task TEXT,
    time_slot TEXT
);

INSERT INTO official_shifts (id, volunteer_name, role, shift_time, age_group, code) VALUES
    (1, 'Jude Thompson', 'choir_assistant', '12:00 PM', 'senior', NULL),
    (2, 'Mateo Cruz', 'choir_assistant', '12:00 PM', 'senior', NULL),
    (3, 'Olivia Dubois', 'choir_assistant', '2:00 PM', 'teen', 'A1'),
    (4, 'Jeff Bezos', 'choir_assistant', '10:00 AM', 'adult', 'X7'),
    (5, 'Kian Rahimi', 'stage_setup', '12:00 PM', 'adult', 'X7'),
    (6, 'Haruto Sato', 'cocoa_station', '10:00 AM', 'adult', 'X7'),
    (7, 'Uma Singh', 'parking_support', '10:00 AM', 'adult', NULL),
    (8, 'Owen Scott', 'parking_support', '10:00 AM', 'adult', 'X7'),
    (9, 'Adil Rahman', 'stage_setup', '2:00 PM', 'adult', 'A1'),
    (10, 'Aaron Diaz', 'choir_assistant', '2:00 PM', 'senior', 'X7'),
    (11, 'Carter Lewis', 'cocoa_station', '10:00 AM', 'senior', 'B2'),
    (12, 'Anya Pavlov', 'stage_setup', '10:00 AM', 'senior', 'OLD'),
    (13, 'Ethan Brown', 'stage_setup', '2:00 PM', 'adult', 'A1'),
    (14, 'Lucia Fernandez', 'choir_assistant', '12:00 PM', 'senior', 'X7'),
    (15, 'Casey Morgan', 'choir_assistant', '12:00 PM', 'teen', 'OLD'),
    (16, 'Olivia Brown', 'stage_setup', '2:00 PM', 'teen', 'X7'),
    (17, 'Lena Fischer', 'cocoa_station', '2:00 PM', 'adult', 'A1'),
    (18, 'Nolan Murphy', 'parking_support', '10:00 AM', 'teen', 'OLD'),
    (19, 'Hazel Turner', 'stage_setup', '12:00 PM', 'adult', 'A1'),
    (20, 'Leo Russell', 'parking_support', '12:00 PM', 'teen', 'OLD'),
    (21, 'Jonah Thompson', 'cocoa_station', '2:00 PM', 'adult', NULL),
    (22, 'Sienna Powell', 'parking_support', '10:00 AM', 'senior', 'A1'),
    (23, 'Emma Svensson', 'parking_support', '12:00 PM', 'adult', 'B2'),
    (24, 'Jonah Wolfe', 'cocoa_station', '2:00 PM', 'senior', 'X7'),
    (25, 'David Johnson', 'parking_support', '12:00 PM', 'adult', 'B2'),
    (26, 'Stella Phillips', 'parking_support', '10:00 AM', 'adult', NULL),
    (27, 'Jonathan Nelson', 'stage_setup', '12:00 PM', 'teen', NULL),
    (28, 'Adam King', 'stage_setup', '10:00 AM', 'senior', NULL),
    (29, 'Tariq Ali', 'cocoa_station', '2:00 PM', 'adult', NULL),
    (30, 'Andre Oliveira', 'parking_support', '2:00 PM', 'teen', 'OLD'),
    (31, 'Ryan Adams', 'parking_support', '10:00 AM', 'teen', 'X7'),
    (32, 'Jordan Torres', 'cocoa_station', '12:00 PM', 'senior', 'OLD'),
    (33, 'Ethan Mitchell', 'parking_support', '10:00 AM', 'teen', NULL),
    (34, 'Evan Bell', 'choir_assistant', '2:00 PM', 'senior', 'A1'),
    (35, 'Andre Oliveira', 'parking_support', '2:00 PM', 'senior', 'A1'),
    (36, 'Natalia Turner', 'stage_setup', '2:00 PM', 'adult', 'B2'),
    (37, 'Kevin Ramirez', 'parking_support', '2:00 PM', 'teen', 'A1'),
    (38, 'Carlos Mendez', 'stage_setup', '10:00 AM', 'adult', 'B2'),
    (39, 'Mira Zhao', 'parking_support', '10:00 AM', 'adult', NULL),
    (40, 'Lila Alexander', 'stage_setup', '2:00 PM', 'adult', 'B2'),
    (41, 'Alina Popov', 'cocoa_station', '12:00 PM', 'adult', 'OLD'),
    (42, 'Sophie Morgan', 'parking_support', '2:00 PM', 'teen', NULL),
    (43, 'Sienna Moreau', 'cocoa_station', '2:00 PM', 'teen', 'X7'),
    (44, 'Charlotte Singh', 'parking_support', '10:00 AM', 'adult', 'B2'),
    (45, 'Brooklyn Parker', 'parking_support', '2:00 PM', 'teen', 'X7'),
    (46, 'James Kim', 'choir_assistant', '12:00 PM', 'senior', 'OLD'),
    (47, 'James Jackson', 'stage_setup', '10:00 AM', 'adult', 'B2'),
    (48, 'Justin Carter', 'choir_assistant', '12:00 PM', 'teen', NULL),
    (49, 'Zara Sheikh', 'stage_setup', '10:00 AM', 'senior', 'B2'),
    (50, 'Isla Torres', 'parking_support', '10:00 AM', 'teen', 'A1'),
    (51, 'Samantha Wright', 'parking_support', '10:00 AM', 'senior', 'B2'),
    (52, 'Mina Youssef', 'choir_assistant', '2:00 PM', 'senior', 'B2'),
    (53, 'Claire Rivera', 'choir_assistant', '2:00 PM', 'teen', 'B2'),
    (54, 'Nia Brown', 'stage_setup', '10:00 AM', 'adult', 'A1'),
    (55, 'Harper Lin', 'stage_setup', '2:00 PM', 'adult', 'X7'),
    (56, 'Eli Brooks', 'cocoa_station', '2:00 PM', 'senior', NULL),
    (57, 'Luca Bianchi', 'stage_setup', '12:00 PM', 'teen', 'OLD'),
    (58, 'Aisha Bennett', 'cocoa_station', '12:00 PM', 'adult', 'OLD'),
    (59, 'Yara Haddad', 'cocoa_station', '10:00 AM', 'senior', 'X7'),
    (60, 'Ravi Patel', 'choir_assistant', '12:00 PM', 'senior', 'OLD'),
    (61, 'Paisley Parker', 'stage_setup', '12:00 PM', 'teen', NULL),
    (62, 'Eve Laurent', 'choir_assistant', '12:00 PM', 'senior', 'OLD'),
    (63, 'Madison Clark', 'cocoa_station', '2:00 PM', 'teen', 'A1'),
    (64, 'Maya Alexander', 'stage_setup', '12:00 PM', 'senior', 'A1'),
    (65, 'Keiko Saito', 'choir_assistant', '2:00 PM', 'teen', 'X7'),
    (66, 'Tomas Garcia', 'cocoa_station', '10:00 AM', 'senior', 'X7'),
    (67, 'Yara Costa', 'cocoa_station', '10:00 AM', 'adult', 'A1'),
    (68, 'Leo Martin', 'choir_assistant', '10:00 AM', 'adult', NULL),
    (69, 'Dara Kim', 'cocoa_station', '2:00 PM', 'senior', 'A1'),
    (70, 'Grace Green', 'parking_support', '12:00 PM', 'senior', 'X7'),
    (71, 'Priya Nair', 'cocoa_station', '12:00 PM', 'senior', 'A1'),
    (72, 'Avery Roberts', 'cocoa_station', '2:00 PM', 'adult', 'OLD'),
    (73, 'Rachel Walker', 'stage_setup', '12:00 PM', 'senior', 'OLD'),
    (74, 'Christopher Hall', 'stage_setup', '12:00 PM', 'teen', 'B2'),
    (75, 'Elias Monroe', 'cocoa_station', '10:00 AM', 'senior', 'OLD'),
    (76, 'Matthew Johnson', 'choir_assistant', '12:00 PM', 'senior', 'OLD'),
    (77, 'Nora Griffin', 'parking_support', '10:00 AM', 'adult', 'OLD'),
    (78, 'Clara Rossi', 'cocoa_station', '10:00 AM', 'teen', 'OLD'),
    (79, 'Fatima Noor', 'cocoa_station', '12:00 PM', 'teen', 'X7'),
    (80, 'Zachary Collins', 'parking_support', '12:00 PM', 'senior', 'A1'),
    (81, 'Kian Rahimi', 'stage_setup', '12:00 PM', 'adult', 'X7'),
    (82, 'Jamal Bryant', 'parking_support', '2:00 PM', 'teen', 'OLD'),
    (83, 'Nick Taylor', 'choir_assistant', '2:00 PM', 'teen', 'OLD'),
    (84, 'Isaac Brooks', 'parking_support', '10:00 AM', 'senior', 'A1'),
    (85, 'Mateo Silva', 'stage_setup', '12:00 PM', 'teen', 'A1'),
    (86, 'Andrew Lewis', 'cocoa_station', '2:00 PM', 'teen', 'X7'),
    (87, 'Elijah Anderson', 'parking_support', '10:00 AM', 'teen', 'A1'),
    (88, 'Peter Lee', 'stage_setup', '2:00 PM', 'teen', NULL),
    (89, 'Casey Morgan', 'choir_assistant', '12:00 PM', 'adult', NULL),
    (90, 'Victoria Hill', 'parking_support', '12:00 PM', 'teen', 'OLD'),
    (91, 'Jonas Muller', 'stage_setup', '12:00 PM', 'adult', 'B2'),
    (92, 'Dylan Bailey', 'cocoa_station', '12:00 PM', 'senior', 'X7'),
    (93, 'Nathan Cooper', 'stage_setup', '2:00 PM', 'senior', 'OLD'),
    (94, 'Diego Ramos', 'choir_assistant', '10:00 AM', 'senior', 'OLD'),
    (95, 'Ralfie Coleman', 'cocoa_station', '12:00 PM', 'adult', 'B2'),
    (96, 'Hiro Tanaka', 'choir_assistant', '10:00 AM', 'teen', NULL),
    (97, 'Isla Wilson', 'parking_support', '2:00 PM', 'adult', 'X7'),
    (98, 'Gianna Russo', 'stage_setup', '10:00 AM', 'teen', 'OLD'),
    (99, 'Leah Wright', 'stage_setup', '2:00 PM', 'adult', 'A1'),
    (100, 'Aaron Carter', 'parking_support', '2:00 PM', 'senior', NULL),
    (101, 'Carmen Diaz', 'parking_support', '2:00 PM', 'adult', 'B2'),
    (102, 'William Becker', 'choir_assistant', '12:00 PM', 'teen', NULL),
    (103, 'Sophia Thomas', 'choir_assistant', '2:00 PM', 'adult', NULL),
    (104, 'Paisley Flores', 'parking_support', '2:00 PM', 'teen', 'A1'),
    (105, 'Stella Richardson', 'cocoa_station', '10:00 AM', 'adult', 'A1'),
    (106, 'Natalie Allen', 'choir_assistant', '2:00 PM', 'teen', 'A1'),
    (107, 'Sheryl Sandberg', 'choir_assistant', '2:00 PM', 'senior', 'B2'),
    (108, 'Kylie Baker', 'cocoa_station', '2:00 PM', 'teen', 'X7'),
    (109, 'Ella Walker', 'parking_support', '12:00 PM', 'senior', 'X7'),
    (110, 'Sarah Wilson', 'stage_setup', '12:00 PM', 'teen', 'OLD'),
    (111, 'Nolan Murphy', 'parking_support', '10:00 AM', 'teen', 'B2'),
    (112, 'Jackson Lee', 'choir_assistant', '2:00 PM', 'teen', NULL),
    (113, 'Rafael Silva', 'parking_support', '12:00 PM', 'adult', 'OLD'),
    (114, 'Noah Davis', 'choir_assistant', '12:00 PM', 'adult', NULL),
    (115, 'Noah Fischer', 'cocoa_station', '2:00 PM', 'senior', 'B2'),
    (116, 'Youssef El-Sayed', 'choir_assistant', '2:00 PM', 'adult', 'X7'),
    (117, 'Jason Stewart', 'cocoa_station', '2:00 PM', 'teen', 'X7'),
    (118, 'Benjamin Patel', 'stage_setup', '12:00 PM', 'senior', 'X7'),
    (119, 'Uma Singh', 'parking_support', '10:00 AM', 'adult', 'X7'),
    (120, 'Aaron Evans', 'cocoa_station', '2:00 PM', 'senior', 'X7'),
    (121, 'Jordan Ward', 'parking_support', '10:00 AM', 'senior', NULL),
    (122, 'Felix Schneider', 'cocoa_station', '10:00 AM', 'senior', 'OLD'),
    (123, 'Bella Foster', 'stage_setup', '10:00 AM', 'adult', 'OLD'),
    (124, 'Audrey Edwards', 'cocoa_station', '12:00 PM', 'senior', 'OLD'),
    (125, 'Marissa Mayer', 'stage_setup', '12:00 PM', 'teen', 'X7'),
    (126, 'Mark Zuckerberg', 'choir_assistant', '2:00 PM', 'senior', NULL),
    (127, 'Lucas Ford', 'cocoa_station', '2:00 PM', 'teen', 'OLD'),
    (128, 'Nora Reed', 'choir_assistant', '12:00 PM', 'teen', 'B2'),
    (129, 'Leo Becker', 'choir_assistant', '10:00 AM', 'senior', 'B2'),
    (130, 'Hugo Laurent', 'cocoa_station', '2:00 PM', 'senior', 'OLD'),
    (131, 'Abigail Hernandez', 'stage_setup', '10:00 AM', 'adult', 'OLD'),
    (132, 'Liam Gallagher', 'choir_assistant', '10:00 AM', 'adult', 'X7'),
    (133, 'Isaac Adler', 'choir_assistant', '2:00 PM', 'senior', 'OLD'),
    (134, 'Lisa Carter', 'choir_assistant', '10:00 AM', 'senior', 'OLD'),
    (135, 'Adrian Cox', 'cocoa_station', '10:00 AM', 'teen', 'B2'),
    (136, 'Ingrid Svensson', 'choir_assistant', '10:00 AM', 'teen', 'A1'),
    (137, 'Derek Hall', 'choir_assistant', '2:00 PM', 'adult', NULL),
    (138, 'Steve Young', 'parking_support', '12:00 PM', 'senior', 'X7'),
    (139, 'Julian Ramirez', 'choir_assistant', '2:00 PM', 'adult', 'OLD'),
    (140, 'Ava Moore', 'choir_assistant', '10:00 AM', 'adult', NULL),
    (141, 'Eve Laurent', 'choir_assistant', '12:00 PM', 'teen', 'A1'),
    (142, 'Ian Landsman', 'parking_support', '10:00 AM', 'senior', 'B2'),
    (143, 'Priya Das', 'parking_support', '2:00 PM', 'teen', 'B2'),
    (144, 'Jonas Eriksen', 'choir_assistant', '2:00 PM', 'adult', 'OLD'),
    (145, 'Tyler Torres', 'cocoa_station', '12:00 PM', 'teen', 'X7'),
    (146, 'Hazel Howard', 'choir_assistant', '10:00 AM', 'senior', 'OLD'),
    (147, 'Arjun Kapoor', 'parking_support', '10:00 AM', 'senior', 'A1'),
    (148, 'Tomas Patterson', 'parking_support', '12:00 PM', 'teen', NULL),
    (149, 'Omar Hussein', 'parking_support', '2:00 PM', 'teen', 'X7'),
    (150, 'Claire Campbell', 'stage_setup', '10:00 AM', 'senior', 'OLD'),
    (151, 'Anthony King', 'cocoa_station', '10:00 AM', 'senior', 'A1'),
    (152, 'Andre Diaz', 'choir_assistant', '2:00 PM', 'senior', 'A1'),
    (153, 'Ava Johnson', 'cocoa_station', '2:00 PM', 'adult', 'X7'),
    (154, 'Mina Henderson', 'cocoa_station', '10:00 AM', 'adult', 'A1'),
    (155, 'Susan Wojcicki', 'choir_assistant', '12:00 PM', 'teen', 'A1'),
    (156, 'Jamal Okafor', 'parking_support', '2:00 PM', 'senior', 'A1'),
    (157, 'Jack Dorsey', 'choir_assistant', '12:00 PM', 'teen', 'B2'),
    (158, 'Gianna Russo', 'stage_setup', '10:00 AM', 'senior', 'X7'),
    (159, 'Sofia Rossi', 'choir_assistant', '12:00 PM', 'adult', 'A1'),
    (160, 'Diego Velasquez', 'stage_setup', '2:00 PM', 'teen', 'A1'),
    (161, 'Lucia Fernandez', 'choir_assistant', '12:00 PM', 'teen', 'X7'),
    (162, 'Joshua Scott', 'stage_setup', '12:00 PM', 'teen', 'OLD'),
    (163, 'Caleb Brown', 'parking_support', '12:00 PM', 'adult', 'B2'),
    (164, 'Nick Wood', 'choir_assistant', '2:00 PM', 'senior', 'OLD'),
    (165, 'Sarah Jenkins', 'cocoa_station', '12:00 PM', 'senior', 'B2'),
    (166, 'Michele Phan', 'cocoa_station', '12:00 PM', 'adult', 'B2'),
    (167, 'Chi Zhang', 'choir_assistant', '12:00 PM', 'adult', NULL),
    (168, 'Skylar Edwards', 'stage_setup', '12:00 PM', 'teen', NULL),
    (169, 'Sofia Kim', 'parking_support', '2:00 PM', 'senior', 'B2'),
    (170, 'Eva Barnes', 'choir_assistant', '2:00 PM', 'teen', NULL),
    (171, 'Brandon Mitchell', 'cocoa_station', '12:00 PM', 'adult', 'B2'),
    (172, 'Mira Chen', 'cocoa_station', '2:00 PM', 'teen', 'X7'),
    (173, 'Sarah Mitchell', 'stage_setup', '12:00 PM', 'teen', 'X7'),
    (174, 'Nia Grant', 'stage_setup', '10:00 AM', 'senior', 'A1'),
    (175, 'Mila Novak', 'choir_assistant', '10:00 AM', 'teen', 'X7'),
    (176, 'Caleb Adams', 'choir_assistant', '10:00 AM', 'senior', NULL),
    (177, 'Zara Ahmed', 'stage_setup', '12:00 PM', 'adult', 'A1'),
    (178, 'Tim Cook', 'choir_assistant', '12:00 PM', 'teen', 'X7'),
    (179, 'Samuel Greene', 'cocoa_station', '12:00 PM', 'senior', 'X7'),
    (180, 'Elon Musk', 'parking_support', '12:00 PM', 'senior', 'OLD'),
    (181, 'Emma Wilson', 'choir_assistant', '12:00 PM', 'senior', 'X7'),
    (182, 'Mila Sanders', 'choir_assistant', '12:00 PM', 'teen', 'X7'),
    (183, 'Eva Schmidt', 'stage_setup', '12:00 PM', 'adult', 'OLD'),
    (184, 'Austin Jenkins', 'stage_setup', '2:00 PM', 'teen', 'A1'),
    (185, 'Jasmine Green', 'stage_setup', '12:00 PM', 'adult', 'OLD'),
    (186, 'Zoe Wilson', 'cocoa_station', '2:00 PM', 'senior', 'X7'),
    (187, 'Anna Reed', 'stage_setup', '2:00 PM', 'senior', 'X7'),
    (188, 'Sara Coleman', 'stage_setup', '10:00 AM', 'senior', 'X7'),
    (189, 'Satya Nadella', 'cocoa_station', '10:00 AM', 'adult', 'OLD'),
    (190, 'Mei Wong', 'stage_setup', '2:00 PM', 'teen', 'A1'),
    (191, 'Rosa Alvarez', 'cocoa_station', '10:00 AM', 'senior', 'A1'),
    (192, 'Lena Schmidt', 'cocoa_station', '12:00 PM', 'senior', 'OLD'),
    (193, 'Tariq Hassan', 'stage_setup', '2:00 PM', 'teen', 'B2'),
    (194, 'Seth Cohen', 'cocoa_station', '12:00 PM', 'senior', 'X7'),
    (195, 'Isabella Laurent', 'parking_support', '12:00 PM', 'adult', 'B2'),
    (196, 'Hugo Garcia', 'cocoa_station', '2:00 PM', 'senior', 'X7'),
    (197, 'Violet Murphy', 'stage_setup', '10:00 AM', 'senior', 'B2'),
    (198, 'Ian Bryant', 'parking_support', '10:00 AM', 'senior', 'A1'),
    (199, 'Lucy Griffin', 'stage_setup', '12:00 PM', 'senior', 'A1'),
    (200, 'Aisha Khan', 'choir_assistant', '12:00 PM', 'teen', 'OLD'),
    (201, 'David Brown', 'cocoa_station', '10:00 AM', 'adult', NULL),
    (202, 'Nova Adams', 'cocoa_station', '10:00 AM', 'teen', 'B2'),
    (203, 'Uma Sanders', 'parking_support', '2:00 PM', 'adult', 'X7'),
    (204, 'Maya Gonzalez', 'stage_setup', '2:00 PM', 'teen', 'OLD'),
    (205, 'Sophia Rossi', 'stage_setup', '12:00 PM', 'adult', 'B2'),
    (206, 'Isaac Adler', 'choir_assistant', '2:00 PM', 'adult', NULL),
    (207, 'Santiago Torres', 'parking_support', '10:00 AM', 'teen', NULL),
    (208, 'Nora Hughes', 'parking_support', '10:00 AM', 'senior', 'X7'),
    (209, 'Benjamin Harris', 'choir_assistant', '12:00 PM', 'adult', 'X7'),
    (210, 'Lily Campbell', 'stage_setup', '12:00 PM', 'teen', 'X7'),
    (211, 'Amina Diallo', 'parking_support', '2:00 PM', 'senior', 'X7'),
    (212, 'Jace Cook', 'choir_assistant', '2:00 PM', 'adult', 'OLD'),
    (213, 'Violet Roberts', 'cocoa_station', '12:00 PM', 'adult', 'B2'),
    (214, 'Caleb Osei', 'cocoa_station', '2:00 PM', 'adult', 'OLD'),
    (215, 'Jace Simmons', 'parking_support', '2:00 PM', 'senior', 'X7'),
    (216, 'Mia Chen', 'choir_assistant', '12:00 PM', 'adult', 'OLD'),
    (217, 'Seth Wood', 'choir_assistant', '2:00 PM', 'adult', 'X7'),
    (218, 'Joseph Garcia', 'parking_support', '12:00 PM', 'senior', 'A1'),
    (219, 'Claire Moreau', 'cocoa_station', '10:00 AM', 'teen', 'X7'),
    (220, 'Isabella White', 'parking_support', '12:00 PM', 'senior', 'X7'),
    (221, 'Hannah Davis', 'cocoa_station', '12:00 PM', 'senior', 'OLD'),
    (222, 'Sabrina Allen', 'choir_assistant', '12:00 PM', 'senior', 'X7'),
    (223, 'Malik Ibrahim', 'stage_setup', '12:00 PM', 'adult', 'B2'),
    (224, 'Linda Zhang', 'parking_support', '10:00 AM', 'teen', 'A1'),
    (225, 'Layla Brooks', 'choir_assistant', '10:00 AM', 'senior', NULL),
    (226, 'Ingrid Jenkins', 'parking_support', '12:00 PM', 'teen', NULL),
    (227, 'Spencer Smith', 'parking_support', '12:00 PM', 'adult', 'A1'),
    (228, 'Charlotte Garcia', 'parking_support', '2:00 PM', 'senior', 'OLD'),
    (229, 'Reed Hastings', 'stage_setup', '2:00 PM', 'senior', 'X7'),
    (230, 'Yusuf Khan', 'cocoa_station', '10:00 AM', 'senior', 'OLD'),
    (231, 'Ellie Long', 'cocoa_station', '2:00 PM', 'adult', 'B2'),
    (232, 'Ravi Sharma', 'choir_assistant', '12:00 PM', 'adult', 'A1'),
    (233, 'Meg Whitman', 'cocoa_station', '2:00 PM', 'teen', 'OLD'),
    (234, 'Ethan Russell', 'choir_assistant', '2:00 PM', 'adult', 'A1'),
    (235, 'Luna Hayes', 'choir_assistant', '12:00 PM', 'adult', NULL),
    (236, 'Hugo Perry', 'stage_setup', '10:00 AM', 'adult', 'OLD'),
    (237, 'Anika Mehta', 'parking_support', '10:00 AM', 'teen', 'X7'),
    (238, 'Lila Dubois', 'choir_assistant', '2:00 PM', 'senior', NULL),
    (239, 'Carmen Bennett', 'cocoa_station', '12:00 PM', 'teen', NULL),
    (240, 'Clara Simmons', 'parking_support', '12:00 PM', 'senior', 'B2'),
    (241, 'Lucy Morris', 'parking_support', '12:00 PM', 'teen', 'A1'),
    (242, 'Audrey Hill', 'parking_support', '12:00 PM', 'teen', NULL),
    (243, 'Zain Malik', 'choir_assistant', '12:00 PM', 'teen', 'X7'),
    (244, 'Daniel Murphy', 'parking_support', '12:00 PM', 'adult', 'X7'),
    (245, 'Liam OConnor', 'cocoa_station', '10:00 AM', 'adult', 'OLD'),
    (246, 'Sara Mitchell', 'cocoa_station', '12:00 PM', 'teen', 'B2'),
    (247, 'Adil Foster', 'stage_setup', '2:00 PM', 'teen', 'A1'),
    (248, 'Omar Qureshi', 'cocoa_station', '10:00 AM', 'senior', 'X7'),
    (249, 'Lucas Thompson', 'cocoa_station', '2:00 PM', 'senior', 'X7'),
    (250, 'Ravi Patel', 'choir_assistant', '12:00 PM', 'adult', 'OLD');

INSERT INTO last_minute_signups (id, volunteer_name, assigned_task, time_slot) VALUES
    (1, 'Jude Thompson', 'Choir', 'noon'),
    (2, 'Mateo Cruz', 'choir', 'noon'),
    (3, 'Olivia Dubois', 'choir', '2 PM'),
    (4, 'Jeff Bezos', 'choir assistant', '10AM'),
    (5, 'Kian Rahimi', 'stage setup', 'noon'),
    (6, 'Haruto Sato', 'cocoa station', '10AM'),
    (7, 'Uma Singh', 'parking_support', '10AM'),
    (8, 'Owen Scott', 'parking', '10AM'),
    (9, 'Adil Rahman', 'Stage-Setup', '2 PM'),
    (10, 'Aaron Diaz', 'Choir', '2 PM'),
    (11, 'Carter Lewis', 'Cocoa Station', '10AM'),
    (12, 'Anya Pavlov', 'stage_setup', '10AM'),
    (13, 'Olivia Brown', 'stage setup', '2 PM'),
    (14, 'Lena Fischer', 'cocoa station', '2 pm'),
    (15, 'Nolan Murphy', 'parking-support', '10AM'),
    (16, 'Hazel Turner', 'stage    setup', 'noon'),
    (17, 'Jonah Wolfe', 'Cocoa Station', '2 PM'),
    (18, 'Stella Phillips', 'parking_support', '10 am'),
    (19, 'Tariq Ali', 'hot cocoa station', '2 pm'),
    (20, 'Ryan Adams', 'parking_support', '10 am'),
    (21, 'Jordan Torres', 'cocoa station', 'noon'),
    (22, 'Evan Bell', 'Choir', '2 pm'),
    (23, 'Kevin Ramirez', 'parking_support', '2 pm'),
    (24, 'Carlos Mendez', 'stage setup', '10AM'),
    (25, 'James Jackson', 'Stage-Setup', '10 am'),
    (26, 'Justin Carter', 'choir', 'noon'),
    (27, 'Mina Youssef', 'choir', '2 pm'),
    (28, 'Yara Haddad', 'hot cocoa station', '10 am'),
    (29, 'Eve Laurent', 'choir assistant', 'noon'),
    (30, 'Madison Clark', 'cocoa station', '2 pm'),
    (31, 'Christopher Hall', 'stage_setup', 'noon'),
    (32, 'Elias Monroe', 'Cocoa Station', '10 am'),
    (33, 'Clara Rossi', 'cocoa station', '10 am'),
    (34, 'Fatima Noor', 'Cocoa Station', 'noon'),
    (35, 'Zachary Collins', 'parking_support', 'noon'),
    (36, 'Nick Taylor', 'Choir', '2 pm'),
    (37, 'Andrew Lewis', 'cocoa station', '2 PM'),
    (38, 'Elijah Anderson', 'parking_support', '10AM'),
    (39, 'Casey Morgan', 'choir assistant', 'noon'),
    (40, 'Dylan Bailey', 'Cocoa Station', 'noon'),
    (41, 'Diego Ramos', 'choir assistant', '10 am'),
    (42, 'Isla Wilson', 'parking_support', '2 PM'),
    (43, 'Gianna Russo', 'stage_setup', '10AM'),
    (44, 'Carmen Diaz', 'parking', '2 PM'),
    (45, 'Paisley Flores', 'parking_support', '2 PM'),
    (46, 'Kylie Baker', 'Cocoa Station', '2 PM'),
    (47, 'Nolan Murphy', 'parking-support', '10 am'),
    (48, 'Noah Fischer', 'cocoa station', '2 pm'),
    (49, 'Youssef El-Sayed', 'choir assistant', '2 pm'),
    (50, 'Uma Singh', 'parking', '10AM'),
    (51, 'Felix Schneider', 'hot cocoa station', '10 am'),
    (52, 'Bella Foster', 'Stage-Setup', '10AM'),
    (53, 'Marissa Mayer', 'Stage-Setup', 'noon'),
    (54, 'Leo Becker', 'choir', '10AM'),
    (55, 'Hugo Laurent', 'cocoa station', '2 PM'),
    (56, 'Isaac Adler', 'choir assistant', '2 pm'),
    (57, 'Claire Campbell', 'stage    setup', '10 am'),
    (58, 'Anthony King', 'hot cocoa station', '10 am'),
    (59, 'Andre Diaz', 'choir', '2 pm'),
    (60, 'Joshua Scott', 'stage setup', 'noon'),
    (61, 'Caleb Brown', 'parking-support', 'noon'),
    (62, 'Sarah Jenkins', 'cocoa station', 'noon'),
    (63, 'Nia Grant', 'stage_setup', '10AM'),
    (64, 'Tim Cook', 'choir assistant', 'noon'),
    (65, 'Emma Wilson', 'Choir', 'noon'),
    (66, 'Aisha Khan', 'choir', 'noon'),
    (67, 'Uma Sanders', 'parking', '2 PM'),
    (68, 'Maya Gonzalez', 'stage setup', '2 PM'),
    (69, 'Benjamin Harris', 'choir', 'noon'),
    (70, 'Amina Diallo', 'parking-support', '2 PM'),
    (71, 'Mia Chen', 'choir', 'noon'),
    (72, 'Isabella White', 'parking_support', 'noon'),
    (73, 'Sabrina Allen', 'Choir', 'noon'),
    (74, 'Ingrid Jenkins', 'parking-support', 'noon'),
    (75, 'Yusuf Khan', 'Cocoa Station', '10AM'),
    (76, 'Ellie Long', 'cocoa station', '2 pm'),
    (77, 'Luna Hayes', 'choir', 'noon'),
    (78, 'Audrey Hill', 'parking', 'noon'),
    (79, 'Daniel Murphy', 'parking_support', 'noon'),
    (80, 'Sara Mitchell', 'hot cocoa station', 'noon'),
    (81, 'Omar Qureshi', 'Cocoa Station', '10 am'),
    (82, 'Ravi Patel', 'choir', 'noon'),
    (83, 'Ingrid Nilsen', 'parking', '10 am'),
    (84, 'Austin Collins', 'stage_setup', '10 am'),
    (85, 'Nolan Henderson', 'stage setup', '10 am'),
    (86, 'Skylar Perry', 'Handwarmer-Handout', 'noon'),
    (87, 'Christian Evans', 'stage    setup', '2 PM'),
    (88, 'Rafael Ross', 'Handwarmer-Handout', '2 PM'),
    (89, 'Lucia Hayes', 'handwarmers', 'noon'),
    (90, 'Bianca Pereira', 'stage_setup', '10 am'),
    (91, 'Colton Stewart', 'Cocoa Station', '2 PM'),
    (92, 'John ONolan', 'snow shoveling', '10AM'),
    (93, 'Caleb Price', 'Choir', '10 am'),
    (94, 'Christian Cook', 'parking-support', '2 PM'),
    (95, 'Eve Patterson', 'parking', 'noon'),
    (96, 'Nora Wilson', 'Handwarmer-Handout', '2 PM'),
    (97, 'Casey Barnes', 'Snow-Shoveling', 'noon'),
    (98, 'Oliver Taylor', 'stage_setup', '2 pm'),
    (99, 'Samuel Lee', 'handwarmers', '2 pm'),
    (100, 'Aaron Francis', 'handwarmer handout', '2 PM'),
    (101, 'Aisha Mohammed', 'cocoa station', '2 pm'),
    (102, 'Sundar Pichai', 'stage_setup', '10AM'),
    (103, 'Sara Johansson', 'cocoa station', 'noon'),
    (104, 'Elias Novak', 'snow shoveling', '2 pm'),
    (105, 'Mia Martin', 'parking', '2 PM'),
    (106, 'Dara Price', 'parking-support', '10 am'),
    (107, 'Keiko Ito', 'parking', 'noon'),
    (108, 'Jude Ross', 'choir assistant', 'noon'),
    (109, 'Gavin Young', 'parking', 'noon'),
    (110, 'Alina Powell', 'parking_support', 'noon'),
    (111, 'Elena Morales', 'handwarmer handout', '10 am'),
    (112, 'Hana Yamamoto', 'shovel', '2 pm'),
    (113, 'Nathan Nelson', 'parking', '10 am'),
    (114, 'Milo Santos', 'handwarmer handout', 'noon'),
    (115, 'Ava Moreau', 'Snow-Shoveling', 'noon'),
    (116, 'Emily Martinez', 'handwarmer handout', 'noon'),
    (117, 'Holly Phillips', 'stage_setup', '2 pm'),
    (118, 'Yusuf Hughes', 'parking_support', '10AM'),
    (119, 'Cameron Rogers', 'Handwarmer-Handout', 'noon'),
    (120, 'Chloe Baker', 'Snow-Shoveling', '2 PM'),
    (121, 'Sienna Rossi', 'Stage-Setup', '2 pm'),
    (122, 'Dominic Patterson', 'Stage-Setup', '10AM'),
    (123, 'Bianca Pereira', 'handwarmer handout', 'noon'),
    (124, 'Kian Perry', 'shovel', '2 PM'),
    (125, 'Colton Powell', 'handwarmer handout', 'noon'),
    (126, 'Layla Davis', 'choir', '2 PM');

