DROP TABLE IF EXISTS passengers;
DROP TABLE IF EXISTS cocoa_cars;

CREATE TABLE passengers (
    passenger_id INT PRIMARY KEY,
    passenger_name TEXT,
    favorite_mixins TEXT[],
    car_id INT
);

CREATE TABLE cocoa_cars (
    car_id INT PRIMARY KEY,
    available_mixins TEXT[],
    total_stock INT
);

INSERT INTO passengers (passenger_id, passenger_name, favorite_mixins, car_id) VALUES
    (1, 'Ava Johnson', ARRAY['vanilla foam'], 2),
    (2, 'Mateo Cruz', ARRAY['caramel drizzle','shaved chocolate','white chocolate'], 2),
    (3, 'Nia Grant', ARRAY['shaved chocolate'], 5),
    (4, 'Hiro Tanaka', ARRAY['shaved chocolate'], 2),
    (5, 'Layla Brooks', ARRAY['crispy rice','dark chocolate','caramel drizzle','cinnamon'], 3),
    (6, 'Ravi Patel', ARRAY['caramel drizzle','shaved chocolate','white chocolate'], 5),
    (7, 'Sofia Kim', ARRAY['cinnamon'], 9),
    (8, 'Jonah Wolfe', ARRAY['cinnamon','dark chocolate'], 7),
    (9, 'Elena Morales', ARRAY['white chocolate','shaved chocolate','caramel drizzle'], 6),
    (10, 'Diego Ramos', ARRAY['shaved chocolate'], 1),
    (11, 'Zara Sheikh', ARRAY['vanilla foam','crispy rice','peppermint'], 4),
    (12, 'Caleb Osei', ARRAY['shaved chocolate','dark chocolate','white chocolate'], 8),
    (13, 'Mila Novak', ARRAY['crispy rice','cinnamon'], 4),
    (14, 'Lucas Ford', ARRAY['vanilla foam','white chocolate','cinnamon'], 4),
    (15, 'Yara Haddad', ARRAY['white chocolate','dark chocolate'], 2),
    (16, 'Omar Qureshi', ARRAY['marshmallow'], 3),
    (17, 'Keiko Ito', ARRAY['vanilla foam','marshmallow'], 7),
    (18, 'Tariq Hassan', ARRAY['dark chocolate','crispy rice','white chocolate','peppermint'], 2),
    (19, 'Mira Zhao', ARRAY['caramel drizzle','marshmallow','cinnamon'], 7),
    (20, 'Bianca Pereira', ARRAY['dark chocolate','peppermint'], 5),
    (21, 'Eva Schmidt', ARRAY['white chocolate','marshmallow'], 5),
    (22, 'Rafael Silva', ARRAY['cinnamon','caramel drizzle'], 3),
    (23, 'Nolan Murphy', ARRAY['caramel drizzle'], 8),
    (24, 'Sara Johansson', ARRAY['marshmallow'], 6),
    (25, 'Ingrid Nilsen', ARRAY['shaved chocolate','peppermint','marshmallow'], 2),
    (26, 'Arjun Kapoor', ARRAY['dark chocolate'], 2),
    (27, 'Nova Adams', ARRAY['cinnamon','dark chocolate'], 9),
    (28, 'Felix Schneider', ARRAY['crispy rice','vanilla foam'], 4),
    (29, 'Tim Cook', ARRAY['crispy rice','vanilla foam'], 6),
    (30, 'Sophia Rossi', ARRAY['white chocolate','dark chocolate','peppermint','marshmallow'], 4),
    (31, 'Liam OConnor', ARRAY['caramel drizzle'], 1),
    (32, 'Olivia Dubois', ARRAY['shaved chocolate','peppermint'], 2),
    (33, 'Emma Svensson', ARRAY['shaved chocolate'], 2),
    (34, 'Noah Fischer', ARRAY['caramel drizzle'], 2),
    (35, 'William Becker', ARRAY['crispy rice','dark chocolate'], 4),
    (36, 'Isabella Laurent', ARRAY['dark chocolate','shaved chocolate'], 8),
    (37, 'James Kim', ARRAY['shaved chocolate','marshmallow','peppermint','caramel drizzle'], 7),
    (38, 'Mia Chen', ARRAY['vanilla foam','white chocolate','shaved chocolate'], 1),
    (39, 'Benjamin Patel', ARRAY['peppermint'], 7),
    (40, 'Charlotte Singh', ARRAY['marshmallow','shaved chocolate','white chocolate'], 4),
    (41, 'Daniel Murphy', ARRAY['cinnamon','vanilla foam','marshmallow','white chocolate'], 8),
    (42, 'Zoe Wilson', ARRAY['marshmallow','dark chocolate'], 9),
    (43, 'Robert Smith', ARRAY['peppermint'], 9),
    (44, 'Emily Johnson', ARRAY['marshmallow'], 4),
    (45, 'David Brown', ARRAY['vanilla foam','dark chocolate'], 8),
    (46, 'Sarah Davis', ARRAY['vanilla foam','peppermint'], 3),
    (47, 'James Simon', ARRAY['peppermint','vanilla foam','cinnamon','shaved chocolate'], 5),
    (48, 'Linda Lee', ARRAY['white chocolate','dark chocolate','marshmallow','vanilla foam'], 5),
    (49, 'Carlos Mendez', ARRAY['peppermint','white chocolate'], 6),
    (50, 'Fatima Noor', ARRAY['peppermint'], 8),
    (51, 'Youssef El-Sayed', ARRAY['peppermint','marshmallow'], 3),
    (52, 'Ian Landsman', ARRAY['marshmallow'], 4),
    (53, 'Nolan Young', ARRAY['marshmallow','shaved chocolate','crispy rice','vanilla foam'], 1),
    (54, 'Ava Martinez', ARRAY['vanilla foam'], 9),
    (55, 'William Chen', ARRAY['crispy rice','shaved chocolate','caramel drizzle'], 6),
    (56, 'Isabella Rodriguez', ARRAY['crispy rice','vanilla foam'], 3),
    (57, 'Zachary Collins', ARRAY['dark chocolate','caramel drizzle','vanilla foam'], 2),
    (58, 'Audrey Edwards', ARRAY['dark chocolate'], 2),
    (59, 'Jason Stewart', ARRAY['white chocolate'], 4),
    (60, 'Lucy Morris', ARRAY['cinnamon','caramel drizzle','peppermint'], 4),
    (61, 'Cameron Rogers', ARRAY['crispy rice','cinnamon','shaved chocolate'], 9),
    (62, 'Aria Blackwood', ARRAY['white chocolate','peppermint','caramel drizzle'], 9),
    (63, 'Felix Whitmore', ARRAY['marshmallow','cinnamon','dark chocolate'], 2),
    (64, 'Luna Hartley', ARRAY['white chocolate'], 3),
    (65, 'Jasper Thorne', ARRAY['crispy rice','shaved chocolate','caramel drizzle'], 6),
    (66, 'Nora Calloway', ARRAY['crispy rice','dark chocolate'], 5),
    (67, 'Silas Merrick', ARRAY['marshmallow'], 7),
    (68, 'Iris Pembroke', ARRAY['peppermint','white chocolate','cinnamon'], 3),
    (69, 'Milo Ashford', ARRAY['cinnamon','dark chocolate','crispy rice'], 7),
    (70, 'Clara Westbrook', ARRAY['marshmallow'], 2),
    (71, 'Owen Fairchild', ARRAY['white chocolate','peppermint'], 6),
    (72, 'Ruby Hawthorne', ARRAY['vanilla foam','cinnamon'], 1),
    (73, 'Finn Lockhart', ARRAY['caramel drizzle','peppermint','cinnamon'], 4),
    (74, 'Violet Sterling', ARRAY['marshmallow','caramel drizzle'], 9),
    (75, 'August Blackwell', ARRAY['cinnamon','shaved chocolate','vanilla foam','marshmallow'], 3),
    (76, 'Hazel Kincaid', ARRAY['peppermint','cinnamon','caramel drizzle','dark chocolate'], 7),
    (77, 'Leo Greyson', ARRAY['crispy rice','cinnamon'], 2),
    (78, 'Stella Beaumont', ARRAY['peppermint','dark chocolate','marshmallow','vanilla foam'], 8),
    (79, 'Miles Brennan', ARRAY['crispy rice','shaved chocolate','marshmallow'], 1),
    (80, 'Ivy Winslow', ARRAY['vanilla foam','caramel drizzle'], 5),
    (81, 'Jack Carmichael', ARRAY['crispy rice'], 6),
    (82, 'Scarlett Dalton', ARRAY['white chocolate','caramel drizzle','peppermint','vanilla foam'], 5),
    (83, 'Oliver Ashby', ARRAY['crispy rice','peppermint'], 2),
    (84, 'Aurora Whitfield', ARRAY['caramel drizzle','white chocolate','shaved chocolate','crispy rice'], 9),
    (85, 'Noah Hastings', ARRAY['vanilla foam'], 4),
    (86, 'Eliza Radcliffe', ARRAY['peppermint','vanilla foam','white chocolate'], 9),
    (87, 'Liam Donovan', ARRAY['caramel drizzle','vanilla foam'], 2),
    (88, 'Penelope Sinclair', ARRAY['caramel drizzle','marshmallow','white chocolate'], 5),
    (89, 'Ethan Marlowe', ARRAY['vanilla foam','caramel drizzle','shaved chocolate'], 5),
    (90, 'Charlotte Waverly', ARRAY['shaved chocolate','vanilla foam'], 7),
    (91, 'Lucas Prescott', ARRAY['crispy rice','vanilla foam'], 9),
    (92, 'Amelia Rosewood', ARRAY['crispy rice'], 5),
    (93, 'Henry Treadwell', ARRAY['vanilla foam','caramel drizzle'], 8),
    (94, 'Sophie Langford', ARRAY['dark chocolate','shaved chocolate','crispy rice','white chocolate'], 3),
    (95, 'Benjamin Fairweather', ARRAY['crispy rice'], 9),
    (96, 'Grace Aldridge', ARRAY['marshmallow','shaved chocolate','caramel drizzle'], 5),
    (97, 'Samuel Kingsley', ARRAY['shaved chocolate','cinnamon'], 1),
    (98, 'Eleanor Morrison', ARRAY['shaved chocolate'], 8),
    (99, 'Daniel Lockwood', ARRAY['dark chocolate'], 7),
    (100, 'Lucy Harrington', ARRAY['vanilla foam','dark chocolate'], 7),
    (101, 'Matthew Sutherland', ARRAY['cinnamon','peppermint'], 2),
    (102, 'Emma Gilmore', ARRAY['shaved chocolate','cinnamon','vanilla foam','caramel drizzle'], 9),
    (103, 'Alexander Stratton', ARRAY['peppermint','shaved chocolate','vanilla foam','white chocolate'], 8),
    (104, 'Abigail Worthington', ARRAY['dark chocolate','caramel drizzle'], 8),
    (105, 'William Beauchamp', ARRAY['white chocolate','dark chocolate','marshmallow','caramel drizzle'], 8),
    (106, 'Hannah Livingston', ARRAY['crispy rice','shaved chocolate','vanilla foam','caramel drizzle'], 5),
    (107, 'James Garrison', ARRAY['shaved chocolate','crispy rice','white chocolate','peppermint'], 5),
    (108, 'Sophia Brookshire', ARRAY['crispy rice','caramel drizzle'], 6),
    (109, 'Theodore Hadley', ARRAY['cinnamon'], 3),
    (110, 'Olivia Carrington', ARRAY['vanilla foam','cinnamon'], 4),
    (111, 'Sebastian Ashworth', ARRAY['vanilla foam'], 7),
    (112, 'Chloe Blackstone', ARRAY['white chocolate','dark chocolate','shaved chocolate'], 1),
    (113, 'Nicholas Montague', ARRAY['vanilla foam','white chocolate'], 1),
    (114, 'Madeline Ramsey', ARRAY['dark chocolate','peppermint','cinnamon','vanilla foam'], 7),
    (115, 'Gabriel Winthrop', ARRAY['white chocolate','shaved chocolate','dark chocolate','marshmallow'], 5),
    (116, 'Alice Merriweather', ARRAY['dark chocolate','peppermint','shaved chocolate','cinnamon'], 7),
    (117, 'Isaac Kendrick', ARRAY['dark chocolate','cinnamon'], 9),
    (118, 'Lillian Holbrook', ARRAY['vanilla foam'], 1),
    (119, 'Caleb Bellamy', ARRAY['vanilla foam'], 3),
    (120, 'Rose Drummond', ARRAY['cinnamon','peppermint','white chocolate','shaved chocolate'], 6),
    (121, 'Elijah Wakefield', ARRAY['dark chocolate','caramel drizzle'], 6),
    (122, 'Margaret Fairbanks', ARRAY['crispy rice','vanilla foam','cinnamon','peppermint'], 8),
    (123, 'Julian Blackburn', ARRAY['white chocolate'], 1),
    (124, 'Eva Templeton', ARRAY['shaved chocolate','marshmallow','vanilla foam'], 1),
    (125, 'Nathan Whitley', ARRAY['shaved chocolate'], 4),
    (126, 'Anna Westfield', ARRAY['cinnamon'], 4),
    (127, 'Aaron Ashcroft', ARRAY['dark chocolate','marshmallow'], 4),
    (128, 'Julia Pendleton', ARRAY['crispy rice','caramel drizzle','marshmallow','white chocolate'], 2),
    (129, 'Connor Redmond', ARRAY['crispy rice','marshmallow'], 1),
    (130, 'Grace Thornhill', ARRAY['vanilla foam','white chocolate','caramel drizzle'], 4),
    (131, 'Zachary Stafford', ARRAY['shaved chocolate'], 2),
    (132, 'Caroline Bannister', ARRAY['marshmallow','peppermint','cinnamon'], 9),
    (133, 'Dylan Blakely', ARRAY['caramel drizzle','marshmallow','crispy rice','white chocolate'], 6),
    (134, 'Katherine Underwood', ARRAY['vanilla foam'], 8),
    (135, 'Tyler Braddock', ARRAY['vanilla foam'], 6),
    (136, 'Victoria Harwood', ARRAY['cinnamon','vanilla foam','marshmallow','caramel drizzle'], 9),
    (137, 'Ryan Beckett', ARRAY['white chocolate','dark chocolate','shaved chocolate'], 7),
    (138, 'Elizabeth Chesterfield', ARRAY['caramel drizzle','shaved chocolate','vanilla foam'], 2),
    (139, 'Jordan Waverly', ARRAY['dark chocolate','shaved chocolate','vanilla foam'], 8),
    (140, 'Sarah Remington', ARRAY['caramel drizzle','peppermint','shaved chocolate','cinnamon'], 3),
    (141, 'Brandon Locklear', ARRAY['shaved chocolate','caramel drizzle','vanilla foam','cinnamon'], 6),
    (142, 'Rachel Wyndham', ARRAY['crispy rice','peppermint','white chocolate'], 4),
    (143, 'Logan Sherwood', ARRAY['shaved chocolate'], 7),
    (144, 'Amanda Fitzroy', ARRAY['white chocolate','shaved chocolate','caramel drizzle','dark chocolate'], 8),
    (145, 'Jackson Thorpe', ARRAY['peppermint','marshmallow','cinnamon','dark chocolate'], 7),
    (146, 'Rebecca Ashcombe', ARRAY['crispy rice','caramel drizzle'], 8),
    (147, 'Cameron Gladstone', ARRAY['vanilla foam','caramel drizzle','cinnamon'], 8),
    (148, 'Jessica Langston', ARRAY['crispy rice','white chocolate','marshmallow'], 2),
    (149, 'Mason Fairmont', ARRAY['caramel drizzle','marshmallow'], 9),
    (150, 'Emily Claridge', ARRAY['shaved chocolate','white chocolate'], 8),
    (151, 'Hunter Bellingham', ARRAY['white chocolate','crispy rice','peppermint'], 4),
    (152, 'Laura Thornbury', ARRAY['shaved chocolate','caramel drizzle','marshmallow'], 5),
    (153, 'Wyatt Alderton', ARRAY['white chocolate'], 3),
    (154, 'Claire Berkshire', ARRAY['peppermint','white chocolate','crispy rice'], 5),
    (155, 'Cole Ashland', ARRAY['dark chocolate','marshmallow'], 1),
    (156, 'Diana Brightwell', ARRAY['dark chocolate','white chocolate','shaved chocolate'], 6),
    (157, 'Aiden Stanfield', ARRAY['peppermint','crispy rice'], 8),
    (158, 'Natalie Warwick', ARRAY['marshmallow'], 7),
    (159, 'Parker Blackmore', ARRAY['marshmallow','peppermint','white chocolate','vanilla foam'], 5),
    (160, 'Morgan Steadman', ARRAY['shaved chocolate'], 2),
    (161, 'Blake Dunwood', ARRAY['shaved chocolate','vanilla foam','white chocolate','dark chocolate'], 5),
    (162, 'Taylor Woodridge', ARRAY['crispy rice','peppermint','white chocolate','caramel drizzle'], 2),
    (163, 'Chase Ashbury', ARRAY['shaved chocolate','crispy rice'], 2),
    (164, 'Madison Clearwater', ARRAY['shaved chocolate','cinnamon'], 9),
    (165, 'Carter Brookfield', ARRAY['cinnamon'], 1),
    (166, 'Ashley Fairhaven', ARRAY['dark chocolate','white chocolate','cinnamon','peppermint'], 4),
    (167, 'Griffin Hartwell', ARRAY['crispy rice','dark chocolate','peppermint'], 4),
    (168, 'Megan Redfield', ARRAY['shaved chocolate','vanilla foam','peppermint'], 9),
    (169, 'Grayson Westmore', ARRAY['cinnamon','crispy rice'], 3),
    (170, 'Nicole Ashridge', ARRAY['peppermint'], 3),
    (171, 'Sawyer Hollingsworth', ARRAY['crispy rice','dark chocolate','peppermint'], 8),
    (172, 'Alexis Thorndale', ARRAY['vanilla foam','crispy rice','dark chocolate'], 9),
    (173, 'Declan Summerfield', ARRAY['dark chocolate','marshmallow','crispy rice','peppermint'], 7),
    (174, 'Samantha Brightwood', ARRAY['crispy rice','peppermint','dark chocolate'], 4),
    (175, 'Tristan Ashbrook', ARRAY['crispy rice'], 1),
    (176, 'Melissa Ravenscroft', ARRAY['dark chocolate','white chocolate'], 5),
    (177, 'Colton Hawthorne', ARRAY['vanilla foam','dark chocolate'], 2),
    (178, 'Lauren Silverton', ARRAY['caramel drizzle','vanilla foam','cinnamon','dark chocolate'], 2),
    (179, 'Landon Whitworth', ARRAY['caramel drizzle','vanilla foam'], 8),
    (180, 'Kayla Mansfield', ARRAY['vanilla foam','peppermint','shaved chocolate'], 2);

INSERT INTO cocoa_cars (car_id, available_mixins, total_stock) VALUES
    (5, ARRAY['white chocolate','shaved chocolate'], 412),
    (2, ARRAY['cinnamon','marshmallow','caramel drizzle'], 359),
    (9, ARRAY['crispy rice','peppermint','caramel drizzle','shaved chocolate'], 354),
    (4, ARRAY['shaved chocolate','white chocolate'], 338),
    (8, ARRAY['vanilla foam','marshmallow'], 263),
    (1, ARRAY['peppermint','crispy rice'], 205),
    (6, ARRAY['shaved chocolate','dark chocolate','crispy rice','cinnamon','peppermint'], 161),
    (7, ARRAY['caramel drizzle','crispy rice','marshmallow','vanilla foam','cinnamon'], 132),
    (3, ARRAY['vanilla foam','peppermint'], 95);

